// 喵星宇宙初始数据
import { Pet, User, MarketListing, Proposal } from './types';

// 生成初始用户
export const createInitialUser = (): User => ({
  address: '5Grw...aEF5',
  balance: 1000,
  votePower: 3750,
  pets: [1, 2, 3],
  createdAt: Date.now(),
});

// 生成初始宠物
export const createInitialPets = (): Pet[] => [
  {
    id: 1,
    name: '小火',
    element: 'fire',
    rarity: 'rare',
    level: 15,
    experience: 1250,
    expToNextLevel: 2000,
    evolutionStage: 1,
    maxEvolutionStage: 4,
    hp: 120,
    maxHp: 120,
    attack: 45,
    defense: 30,
    speed: 50,
    critRate: 15,
    status: 'idle',
    personality: {
      extroversion: 70,
      warmth: 80,
      humor: 60,
      curiosity: 75,
      responsibility: 50,
    },
    skills: [
      { id: 'fire_strike', name: '火焰冲击', level: 3, damage: 45, manaCost: 15, type: 'attack', icon: '🔥', description: '释放火焰攻击敌人' },
      { id: 'fire_shield', name: '烈焰护盾', level: 2, damage: 0, manaCost: 20, type: 'defense', icon: '🛡️', description: '召唤火焰护盾保护自己' },
    ],
    battleStats: { wins: 28, losses: 12, winRate: 70 },
    createdAt: Date.now() - 86400000 * 30,
  },
  {
    id: 2,
    name: '水灵',
    element: 'water',
    rarity: 'epic',
    level: 22,
    experience: 800,
    expToNextLevel: 3000,
    evolutionStage: 2,
    maxEvolutionStage: 4,
    hp: 180,
    maxHp: 180,
    attack: 38,
    defense: 55,
    speed: 42,
    critRate: 12,
    status: 'idle',
    personality: {
      extroversion: 40,
      warmth: 90,
      humor: 50,
      curiosity: 60,
      responsibility: 85,
    },
    skills: [
      { id: 'water_wave', name: '水波术', level: 4, damage: 40, manaCost: 12, type: 'attack', icon: '🌊', description: '释放水波攻击' },
      { id: 'heal', name: '治愈之泉', level: 3, damage: -50, manaCost: 25, type: 'defense', icon: '💧', description: '恢复生命值' },
      { id: 'ice_spike', name: '冰锥术', level: 2, damage: 55, manaCost: 20, type: 'special', icon: '❄️', description: '召唤冰锥攻击' },
    ],
    battleStats: { wins: 45, losses: 8, winRate: 85 },
    createdAt: Date.now() - 86400000 * 60,
  },
  {
    id: 3,
    name: '暗影',
    element: 'shadow',
    rarity: 'legendary',
    level: 35,
    experience: 2500,
    expToNextLevel: 5000,
    evolutionStage: 3,
    maxEvolutionStage: 4,
    hp: 250,
    maxHp: 250,
    attack: 75,
    defense: 45,
    speed: 80,
    critRate: 25,
    status: 'idle',
    personality: {
      extroversion: 20,
      warmth: 30,
      humor: 40,
      curiosity: 95,
      responsibility: 70,
    },
    skills: [
      { id: 'shadow_strike', name: '暗影突袭', level: 5, damage: 70, manaCost: 18, type: 'attack', icon: '🌑', description: '从暗影中发起突袭' },
      { id: 'void', name: '虚空', level: 4, damage: 90, manaCost: 30, type: 'special', icon: '🕳️', description: '召唤虚空吞噬敌人' },
      { id: 'stealth', name: '隐匿', level: 3, damage: 0, manaCost: 15, type: 'defense', icon: '👻', description: '隐入暗影躲避攻击' },
      { id: 'nightmare', name: '噩梦', level: 2, damage: 100, manaCost: 40, type: 'special', icon: '😈', description: '释放噩梦造成巨大伤害' },
    ],
    battleStats: { wins: 120, losses: 15, winRate: 89 },
    createdAt: Date.now() - 86400000 * 120,
  },
];

// 生成初始市场数据
export const createInitialMarket = (): MarketListing[] => [
  {
    id: 1,
    petId: 101,
    petName: '烈焰之心',
    element: 'fire',
    rarity: 'legendary',
    level: 35,
    price: 500,
    seller: '5FHn...eVkZ',
    type: 'fixed',
    endsAt: Date.now() + 86400000 * 7,
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: 2,
    petId: 102,
    petName: '深海守护者',
    element: 'water',
    rarity: 'epic',
    level: 28,
    price: 150,
    seller: '5DAn...kLmP',
    type: 'auction',
    highestBid: 180,
    highestBidder: '5Xyz...aBcD',
    endsAt: Date.now() + 3600000 * 2.5,
    createdAt: Date.now() - 86400000 * 1,
  },
  {
    id: 3,
    petId: 103,
    petName: '暗影猎手',
    element: 'shadow',
    rarity: 'rare',
    level: 20,
    price: 80,
    seller: '5Abc...dEfG',
    type: 'fixed',
    endsAt: Date.now() + 86400000 * 5,
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: 4,
    petId: 104,
    petName: '光明使者',
    element: 'light',
    rarity: 'mythic',
    level: 50,
    price: 2000,
    seller: '5Grw...aEF5',
    type: 'auction',
    highestBid: 2500,
    highestBidder: '5Qrs...tUvW',
    endsAt: Date.now() + 3600000 * 5.25,
    createdAt: Date.now() - 86400000 * 4,
  },
];

// 生成初始提案数据
export const createInitialProposals = (): Proposal[] => [
  {
    id: 1,
    title: '增加战斗奖励池',
    description: '提议从国库拨款 50,000 COS 用于增加战斗奖励池，激励更多玩家参与 PVE 和 PVP 战斗。预计可提升日活跃用户 30%。',
    type: 'treasury',
    proposer: '5Grw...aEF5',
    status: 'active',
    yesVotes: 45000,
    noVotes: 12000,
    totalVotes: 57000,
    quorum: 12500,
    endsAt: Date.now() + 86400000 * 2 + 3600000 * 5,
    createdAt: Date.now() - 86400000 * 5,
    voters: {},
  },
  {
    id: 2,
    title: '降低交易手续费至 2%',
    description: '建议将市场交易手续费从 2.5% 降低至 2%，以吸引更多交易，提升市场流动性。',
    type: 'parameter',
    proposer: '5FHn...eVkZ',
    status: 'active',
    yesVotes: 28000,
    noVotes: 35000,
    totalVotes: 63000,
    quorum: 12500,
    endsAt: Date.now() + 86400000 * 5 + 3600000 * 12,
    createdAt: Date.now() - 86400000 * 3,
    voters: {},
  },
  {
    id: 3,
    title: '新增神话级宠物',
    description: '提议新增 3 种神话级宠物：凤凰、麒麟、青龙。每种限量 100 只，通过特殊活动获取。',
    type: 'general',
    proposer: '5DAn...kLmP',
    status: 'passed',
    yesVotes: 78000,
    noVotes: 15000,
    totalVotes: 93000,
    quorum: 12500,
    endsAt: Date.now() - 86400000 * 2,
    createdAt: Date.now() - 86400000 * 10,
    voters: {},
  },
];
